import {
  LucideArrowUp,
  LucideBot,
  LucideBrain,
  LucideCalculator,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideCode,
  LucideCreditCard,
  LucideCrown,
  LucideDownload,
  LucideEye,
  LucideEyeOff,
  LucideFileSearch,
  LucideFileText,
  LucideGlobe,
  LucideLogOut,
  LucideMessageSquareText,
  LucideMoon,
  LucidePlus,
  LucideSearch,
  LucideSettings,
  LucideShield,
  LucideSliders,
  LucideSparkles,
  LucideSquare,
  LucideSun,
  LucideTrash,
  LucideUpload,
  LucideUsers,
  LucideWrench,
  LucideX,
  LucideZap,
} from '@lucide/angular';

/**
 * Every icon the app uses by name (`<svg lucideIcon="file-text">`). Registered once in
 * app.config.ts and in specs; only icons listed here end up in the bundle.
 */
export const APP_ICONS = [
  LucideArrowUp,
  LucideBot,
  LucideBrain,
  LucideCalculator,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideCode,
  LucideCreditCard,
  LucideCrown,
  LucideDownload,
  LucideEye,
  LucideEyeOff,
  LucideFileSearch,
  LucideFileText,
  LucideGlobe,
  LucideLogOut,
  LucideMessageSquareText,
  LucideMoon,
  LucidePlus,
  LucideSearch,
  LucideSettings,
  LucideShield,
  LucideSliders,
  LucideSparkles,
  LucideSquare,
  LucideSun,
  LucideTrash,
  LucideUpload,
  LucideUsers,
  LucideWrench,
  LucideX,
  LucideZap,
];

